version: "3"
services:
  app:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: 'kafka_default'
    volumes:
      - .:/usr/app/ms_emails
    ports:
      - "3000:3000"
